---
version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker-config/nginx/Dockerfile
      args:
        - SSL_CERT_DOMAIN=${SSL_CERT_DOMAIN:-craft.test}
    ports:
      - 80:80
      - 443:443
    volumes:
      - cpresources:/var/www/html/web/cpresources
      - ./web:/var/www/html/web:cached
      - ssl-certs:/etc/ssl/self-signed

  mysql:
    platform: linux/x86_64
    image: mysql:5.7.29
    volumes:
      - db:/var/lib/mysql
      - ./.docker-config/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
      MYSQL_DATABASE: craft_development

  redis:
    image: redis:5.0

  php:
    image: craft_php
    build:
      context: .
      dockerfile: ./.docker-config/php/Dockerfile
    entrypoint: ./.docker-config/php/entrypoint.sh
    command: ["docker-php-entrypoint", "php-fpm"]
    expose:
      - 9000
    volumes:
      - cpresources:/var/www/html/web/cpresources
      - storage:/var/www/html/storage
      - .:/var/www/html:cached
    environment:
      - ENVIRONMENT=dev
      - DB_DSN=mysql:host=mysql;port=3306;dbname=craft_development
      - DB_DRIVER=mysql
      - DB_USER=craft
      - DB_PASSWORD=craft
      - DB_TABLE_PREFIX
      - SECURITY_KEY=asdfasdfasdfasdfasdf
      - APP_ID=craft
      - REDIS_HOST=redis
      - PRIMARY_SITE_URL=${PRIMARY_SITE_URL:-http://craft.test}
      - XDEBUG_MODE

  mysql_test:
    image: mysql:5.7.29
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
      MYSQL_DATABASE: craft_test

  test:
    image: craft_php
    volumes:
      - .:/var/www/html
    environment:
      - ENVIRONMENT=test
      - DB_DSN=mysql:host=mysql_test;port=3306;dbname=craft_test
      - DB_USER=craft
      - DB_PASSWORD=craft
      - DB_TABLE_PREFIX
      - SECURITY_KEY=asdfasdfasdfasdfasdf
      - PRIMARY_SITE_URL=http://craft.test
      - XDEBUG_MODE

volumes:
  db:
  cpresources:
  storage:
  ssl-certs:
