field: 7d121022-1fa4-4579-a397-39c22c5e346c # Page Blocks
fieldLayouts:
  02d80339-d9b6-40bb-af40-3c502dd42c49:
    tabs:
      -
        elements:
          -
            fieldUid: 09866fbe-21ff-41d8-8a1f-17eab651bfc7 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2258c2fe-3eec-4221-aefe-152ce629580f
            warning: null
            width: 100
        name: Content
        uid: 38eba639-9033-4225-9b23-ae020ea05575
fields:
  09866fbe-21ff-41d8-8a1f-17eab651bfc7: # Heading
    columnSuffix: zvnxavsk
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cta
name: CTA
sortOrder: 1
